# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 14:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('question_type', models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('freetext', 'Freeform Input')], max_length=50)),
                ('question', models.CharField(max_length=200)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('response_correct', models.CharField(max_length=200)),
                ('response_incorrect', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
