# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quizzes.Question'),
        ),
    ]
