# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20160425_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
